#!/bin/bash
cd ~
dpkg -S nano | grep "\.nanorc$" | awk '{print ("include " $2)}' > ~/.nanorc
wget -O ~/.bashrc https://github.com/nickwild93/cookbook/blob/main/install_shell_colors/.bashrc
wget -O ~/.dircolors https://github.com/nickwild93/cookbook/blob/main/install_shell_colors/.dircolors
echo Copy to root
sudo cp -v .bashrc .nanorc .dircolors /root/
echo
echo Copy to all
sudo cp -v .bashrc .nanorc .dircolors /etc/skel/
